TRUNCATE TABLE "salons" CASCADE;
TRUNCATE TABLE "profiles" CASCADE;
TRUNCATE TABLE "appointments" CASCADE;
TRUNCATE TABLE "gift_cards" CASCADE;
TRUNCATE TABLE "loyalty_balances" CASCADE;
TRUNCATE TABLE "point_transactions" CASCADE;
TRUNCATE TABLE "practitioners" CASCADE;
TRUNCATE TABLE "services" CASCADE;
