'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { NORDIC_COUNTRIES } from '@/data/nordic-data';

type Language = 'Svenska' | 'Norska' | 'Danska' | 'Finska' | 'Isländska' | 'English';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    currency: string;
    setCurrency: (currency: string) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    'Svenska': {
        'search_title': 'Hitta din nästa glow up',
        'search_subtitle': 'Sök på behandlingar eller salonger i din närhet',
        'search_placeholder': 'Vad letar du efter? (t.ex. naglar, fransar...)',
        'search_in': 'Sök i',
        'municipality': 'Kommun',
        'search_button': 'Sök',
        'salon_services': 'Tjänster',
        'salon_about': 'Om oss',
        'salon_reviews': 'Recensioner',
        'salon_directions': 'Vägbeskrivning',
        'salon_choose_time': 'Välj tid',
        'salon_confirm_booking': 'Bekräfta bokning',
        'salon_choose_provider': 'Välj utförare',
        'salon_book_now': 'Boka nu',
        'salon_booking_confirmed': 'Bokningen bekräftad!',
        'salon_date_time': 'Datum & Tid',
        'explore_search_placeholder_2': 'Behandling eller salong...',
        'explore_filter_near_me': 'Nära mig',
        'explore_filter_available_today': 'Ledigt idag',
        'explore_filter_top_rating': 'Toppbetyg',
        'explore_filter_under_price': 'Under 500',
        'explore_filter_new': 'Nya utförare',
        'explore_clear_filters': 'Rensa alla',
        'explore_top_city_title': 'Topp i din kommun',
        'explore_top_city_desc': 'Högst betyg bland utförare i ditt område',
        'explore_quick_times_title': 'Snabba tider',
        'explore_quick_times_desc': 'Boka snabbt hos premium-utförare',
        'explore_new_providers_title': 'Nya utförare',
        'explore_new_providers_desc': 'Nyligen anslutna till Glowbook',
        'explore_search_results': 'Sökresultat',
        'explore_all_providers': 'Alla utförare',
        'explore_sort_recommended': 'Rekommenderat',
        'explore_sort_rating': 'Högst betyg',
        'explore_sort_price': 'Lägst pris',
        'footer_desc': 'Premium bokningsplattform för skönhet & wellness. Kopplar samman kunder med de bästa utförarna.',
        'footer_quick_links': 'Snabblänkar',
        'footer_explore': 'Utforska',
        'footer_register': 'Registrera företag',
        'footer_legal': 'Juridiskt',
        'footer_policies': 'Policies & Användarvillkor',
        'footer_privacy': 'Integritetspolicy (GDPR)',
        'footer_cookies': 'Cookies',
        'footer_platform_online': 'Platform Online',
        'premium_experience': 'Premium Booking Experience',
        'view_all': 'Visa alla',
        'more_categories': 'Fler Kategorier',
        'find_treatment_title': 'Hitta din nästa behandling nära dig',
        'find_treatment_desc': 'Vi finns i hela Norden. Från Stockholm till Helsingfors. Upptäck de bästa salongerna och frilansarna i din stad.',
        'search_your_city': 'Sök i din stad',
        'all_cities': 'Hela Sverige',
        'popular_searches': 'Populära sökningar',
        'popular_categories': 'Populära Kategorier',
        'found_category': 'Vi hittade kategorin:',
        'discover': 'Upptäck',
        'view_all_in': 'Visa alla inom',
        'nails': 'Naglar',
        'lashes': 'Fransar',
        'massage': 'Massage',
        'hair': 'Frisör',
        'facial': 'Ansiktsbehandling',
        'nav_bookings': 'Bokningar',
        'nav_favorites': 'Favoriter',
        'nav_support': 'Support',
        'nav_search': 'Sök',
        'nav_giftcards': 'Presentkort',
        'nav_settings': 'Inställningar',
        'nav_guides': 'Rådgivning',
        'nav_rewards': 'Rewards',
        'nav_inbox': 'Inkorg',
        'nav_dashboard': 'Översikt',
        'action_register_business': 'Starta som studio',
        'action_login': 'Logga in',
        'my_pages': 'Mina sidor',
        'location_title': 'Välj Plats',
        'location_search_placeholder': 'Sök kommun...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'En problemfri upplevelse för både kunder och utförare.\nIngen krånglig administration, bara ren fokus på passion.',
        'home_hero_cta_book': 'Boka tid',
        'home_hero_cta_register': 'Starta som studio',
        'home_categories_title': 'Våra Kategorier',
        'home_categories_subtitle': 'Handplockade experter inom skönhet och hälsa',
        'why_title': 'Varför Glowbook',
        'why_card_1_title': 'Premiumkunder',
        'why_card_1_desc': 'Nå rätt målgrupp och bygg en starkare kundbas',
        'why_card_2_title': 'Smart synlighet',
        'why_card_2_desc': 'Syns baserat på kvalitet, inte bara pris',
        'why_card_3_title': 'Enkel bokning',
        'why_card_3_desc': 'Allt på ett ställe utan krångel',
        'why_card_4_title': 'Bygg ditt varumärke',
        'why_card_4_desc': 'Glowbook är inte bara bokning, det är status',
        'home_view_all': 'Visa alla',
        'cat_nails_name': 'Naglar',
        'cat_nails_desc': 'Minimalistisk nagelvård & design',
        'cat_lashes_name': 'Fransar & Bryn',
        'cat_lashes_desc': 'Lyft blicken med perfekt form',
        'cat_massage_name': 'Massage',
        'cat_massage_desc': 'Djupgående avslappning för sinnet',
        'cat_skin_name': 'Hudvård',
        'cat_skin_desc': 'Återfuktande ansiktvård & lyster',
        'cat_hair_name': 'Hårvård',
        'cat_hair_desc': 'Klippning, färg & styling',
        'cat_injection_name': 'Estetisk Injektion',
        'cat_injection_desc': 'Fillers, botox & hudföryngring',
        'cat_tattoo_name': 'Tatuering',
        'cat_tattoo_desc': 'Konst på hud, från fina linjer till realism',
        'cat_spa_name': 'Spa',
        'cat_spa_desc': 'Total avkoppling & wellness',
        'cat_makeup_name': 'Makeup',
        'cat_makeup_desc': 'Professionell styling för varje tillfälle',
        'cat_footcare_name': 'Fotvård',
        'cat_footcare_desc': 'Medicinsk & kosmetisk fotvård',
        'cat_chiro_name': 'Kiropraktik',
        'cat_chiro_desc': 'Led- & muskelbehandling',
        'cat_naprapathy_name': 'Naprapati',
        'cat_naprapathy_desc': 'Manuell behandling av smärta',
        'cat_teeth_name': 'Tandblekning',
        'cat_teeth_desc': 'Professionell vitare leende',
        'cat_piercing_name': 'Piercing',
        'cat_piercing_desc': 'Säker & stilren piercing',
        'cat_barber_name': 'Barberare',
        'cat_barber_desc': 'Klassisk herrklippning & rakning',
        'onboarding_title_1': 'Definiera din studio',
        'onboarding_title_2': 'Vem står bakom?',
        'onboarding_title_3': 'Välj din growth-plan',
        'onboarding_title_4': 'Glowbook Checkout',
        'onboarding_desc_1': 'Låt premiumkunder hitta dig i din stad.',
        'onboarding_desc_2': 'Dina uppgifter är säkra och krypterade.',
        'onboarding_desc_3': 'Välj bindningstid för att sänka din månadskostnad.',
        'onboarding_desc_4': 'Slutför din beställning säkert via Stripe.',
        'onboarding_step_1': 'Verksamhet',
        'onboarding_step_2': 'Personligt',
        'onboarding_step_3': 'Abonnemang',
        'onboarding_step_4': 'Betalning',
        'label_business_name': 'Verksamhetens Namn',
        'placeholder_business_name': 'T.ex. Glow Nails & Spa',
        'label_category': 'Kategori',
        'label_country': 'Land',
        'label_municipality': 'Kommun',
        'label_address': 'Adress',
        'label_optional': '(Valfritt)',
        'btn_next': 'Nästa',
        'btn_back': 'Tillbaka',
        'btn_complete_klarna': 'Slutför & Aktivera via Stripe',
        'dash_welcome': 'Välkommen',
        'dash_overview': 'Översikt',
        'dash_stat_bookings': 'Bokningar idag',
        'dash_stat_customers': 'Nya kunder',
        'dash_stat_revenue': 'Intäkter',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Kunder',
        'dash_nav_customers_desc': 'Se alla dina befintliga kunder, historik och kontaktuppgifter.',
        'dash_nav_services': 'Tjänster',
        'dash_nav_services_desc': 'Skapa nya tjänster, sätt priser och tider, samt anpassa din profil.',
        'dash_nav_finance': 'Ekonomi',
        'dash_nav_finance_desc': 'Se intäkter från Klarna och godkänn betalningar gjorda på plats.',
        'dash_nav_settings': 'Inställningar',
        'dash_nav_settings_desc': 'Hantera dina salongsuppgifter, personliga info och medlemskap.',
        'dash_bookings_title': 'Bokningar',
        'dash_new_booking': 'Ny bokning',
        'dash_no_bookings': 'Inga bokningar än',
        'dash_no_bookings_desc': 'Det finns inga bokningar registrerade för denna vecka.',
        'settings_title': 'Inställningar',
        'settings_desc': 'Hantera din profil, dina uppgifter och ditt medlemskap.',
        'tab_profile': 'Profil & Konto',
        'tab_membership': 'Medlemskap',
        'tab_notifications': 'Notiser',
        'tab_templates': 'Meddelandemallar',
        'templates_title': 'Dina meddelandemallar',
        'templates_desc': 'Skapa färdiga svar för vanliga frågor som vägbeskrivning och bokningspolicy.',
        'templates_label_directions': 'Vägbeskrivning',
        'templates_label_policy': 'Bokningspolicy',
        'templates_label_preparation': 'Inför besöket',
        'templates_save_btn': 'Spara alla mallar',
        'tab_practitioners': 'Utförare',
        'practitioners_title': 'Hantera utförare',
        'practitioners_desc': 'Lägg till personal på ditt konto så att kunder kan välja vem de vill boka hos.',
        'practitioners_add_btn': 'Lägg till utförare',
        'label_select_practitioner': 'Välj utförare',
        'label_preferred_practitioner': 'Önskad utförare',
        'label_total_cost': 'Totalkostnad',
        'label_per_month': 'per månad',
        'share_link_title': 'Dela ledig tid',
        'share_link_desc': 'Generera en länk som du kan dela på Instagram så att dina kunder kan boka direkt.',
        'share_link_btn': 'Hämta länk',
        'verification_modal_title': 'Verifierat konto',
        'verification_modal_desc': 'Ladda upp ditt certifikat, gesällbrev eller annat bevis på din kompetens. Våra administratörer granskar din profil manuellt inom en vecka.',
        'verification_upload_btn': 'Ladda upp diplom/certifikat',
        'verification_submit_btn': 'Skicka för granskning',
        'verification_status_pending': 'Granskning pågår (beräknat 7 dagar)',
        'tab_marketing': 'Marknadsföring',
        'tab_reviews': 'Recensioner',
        'reviews_title': 'Hantera recensioner',
        'reviews_desc': 'Se vad dina kunder tycker och svara på deras feedback.',
        'review_reply_label': 'Ditt svar',
        'review_reply_placeholder': 'Skriv ett svar...',
        'review_reply_btn': 'Svara',
        'review_replied': 'Svar skickat!',
        'marketing_title': 'Dela din profil',
        'marketing_desc': 'Hitta verktyg för att nå ut till fler kunder och förenkla bokningen.',
        'profile_link_label': 'Din profil-länk',
        'copy_link_btn': 'Kopiera länk',
        'link_copied': 'Länken kopierad!',
        'ig_link_label': 'Länk för Instagram Bio',
        'ig_link_desc': 'Använd denna länk för att kunden ska komma direkt till dina bokningsbara tider.',
        'qr_title': 'Din QR-kod',
        'qr_desc': 'Ladda ner din unika QR-kod och använd den på speglar, visitkort eller i sociala medier.',
        'download_qr': 'Ladda ner QR (PNG)',
        'booking_card_title': 'Dina Bokningskort',
        'booking_card_desc': 'Auto-generera vackra bilder för din Instagram Story eller inlägg.',
        'card_tpl_available': 'Lediga tider',
        'card_tpl_new_service': 'Ny behandling',
        'card_tpl_last_slots': 'Sista luckorna',
        'download_card': 'Spara som bild',
        'next_available_label': 'Nästa lediga tid',
        'settings_salon_title': 'Salongsuppgifter',
        'settings_personal_title': 'Personliga Uppgifter',
        'label_first_name': 'Förnamn',
        'label_last_name': 'Efternamn',
        'label_email': 'Email',
        'btn_save_changes': 'Spara alla ändringar',
        'msg_changes_saved': 'Ändringar sparade',
        'logout': 'Logga ut',
        'action_register': 'Skapa konto',
        'role_customer': 'Kund',
        'role_provider': 'Utförare',
        'role_admin': 'Admin',
        'label_password': 'Lösenord',
        'action_login_prompt': 'Har du redan ett konto?',
        'msg_fill_all_fields': 'Vänligen fyll i alla obligatoriska fält',
        'btn_change': 'Ändra',
        'cal_today': 'Idag',
        'cal_week': 'Vecka',
        'cal_add_slot': 'Lägg ut tider',
        'cal_post_times': 'Lägg ut tider i en ram',
        'cal_go_to': 'Gå till kalender',
        'btn_save_schedule': 'Spara schema',
        'explore_title': 'Upptäck skönhet',
        'salons_found': 'salonger hittades',
        'filter_placeholder': 'Filtrera resultat...',
        'found': 'Hittade',
        'no_salons_found': 'Inga salonger hittades',
        'no_salons_desc': 'Prova att ändra din sökning eller filtrering.',
        'new_search_link': 'Gör en ny sökning',
        'free_today': 'Ledigt idag',
        'view_profile': 'Visa profil',
        'from': 'Från',
        'in': 'i',
        'action_manage_customers': 'Hantera kunder',
        'action_edit_menu': 'Redigera meny',
        'action_view_payouts': 'Se utbetalningar',
        'action_go_to_settings': 'Gå till inställningar',
        'label_address_placeholder': 'Gatuadress',
        'label_main_category': 'Huvudkategori',
        'msg_contact_support_category': 'Kontakta support för att byta bransch-kategori.',
        'label_your_membership': 'Ditt medlemskap',
        'label_status_active': 'Aktivt',
        'label_months': 'månader',
        'action_upgrade_plan': 'Uppgradera plan',
        'action_downgrade_cancel': 'Nedgradera / Avsluta',
        'desc_notifications_settings': 'Hantera dina aviseringsinställningar.',
        'notif_new_bookings': 'Nya bokningar',
        'notif_new_bookings_desc': 'Få meddelande när en kund bokar en tid',
        'notif_cancellations': 'Avbokningar',
        'notif_cancellations_desc': 'Meddelas när en bokning avbokas',
        'notif_reminders': 'Påminnelser',
        'notif_reminders_desc': 'Daglig sammanfattning av kommande bokningar',
        'notif_marketing': 'Marknadsföring',
        'notif_marketing_desc': 'Nyheter och erbjudanden från Glowbook',
        'notif_klarna_connecting': 'Ansluter till säker betalning...',
        'notif_klarna_processing': 'Bearbetar prenumeration...',
        'notif_klarna_success': 'Betalning godkänd!',
        'notif_klarna_redirecting': 'Dirigerar dig till din dashboard...',
        'notif_klarna_secure': 'Krypterad och säker anslutning',
        'action_cancel_purchase': 'Avbryt köp',
        'label_amount_to_pay': 'Belopp att betala nu',
        'msg_klarna_subscription': 'Hanteras säkert via Stripe',
        'label_select_category': 'Välj kategori',
        'msg_personal_data_warning': 'Dessa uppgifter används endast för verifiering och fakturering. De kommer inte att visas publikt på din profil.',
        'label_last_name_placeholder': 'Ditt efternamn',
        'label_first_name_placeholder': 'Ditt förnamn',
        'label_tier_start_desc': '20 bokningar/månad',
        'label_tier_pro_desc': 'Väx snabbare & syns mer',
        'label_tier_studio_desc': 'för större salonger',
        'label_most_popular': 'MEST POPULÄR',
        'label_total': 'Totalt',
        'msg_one_month_free': '1 månad gratis',
        'label_order_summary': 'Din Beställning',
        'label_subscription_length': 'Abonnemangslängd',
        'msg_terms_agreement': 'Genom att gå vidare bekräftar du att du godkänner Glowbooks användarvillkor och integritetspolicy.',
        'label_renewal_automatic': 'Automatisk förnyelse',
        'action_manage_subscription': 'Hantera abonnemang',
        'label_active': 'Aktiv',
        'action_select': 'Välj',
        'notif_payment_notice': 'Betalningsinformation',
        'msg_payment_one_time': 'Ditt abonnemang förnyas automatiskt via Stripe.',
        'btn_save_subscription': 'Uppdatera abonnemang',
        'day_monday': 'Måndag',
        'day_tuesday': 'Tisdag',
        'day_wednesday': 'Onsdag',
        'day_thursday': 'Torsdag',
        'day_friday': 'Fredag',
        'day_saturday': 'Lördag',
        'day_sunday': 'Söndag',
        'msg_invalid_time_range': 'Sluttid måste vara efter starttid',
        'salon_appearance_title': 'Salongens Utseende',
        'salon_appearance_desc': 'Ladda upp bilder som representerar din verksamhet.',
        'label_background_image': 'Bakgrundsbild (1200x400)',
        'action_change_background': 'Ändra bakgrund',
        'action_update': 'Uppdatera',
        'action_create_service': 'Skapa ny tjänst',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Förslag för din kategori',
        'label_service_name': 'Tjänstens namn',
        'label_price': 'Pris',
        'label_time': 'Tid',
        'label_description': 'Beskrivning',
        'placeholder_description': 'Berätta kort om tjänsten...',
        'btn_save_service': 'Spara tjänst'
    },
    'Norska': {
        'search_title': 'Finn din neste glow up',
        'search_subtitle': 'Søk etter behandlinger eller salonger i nærheten',
        'search_placeholder': 'Hva leter du etter? (f.eks. negler, vipper...)',
        'search_in': 'Søk i',
        'municipality': 'Kommune',
        'search_button': 'Søk',
        'salon_services': 'Tjenester',
        'salon_about': 'Om oss',
        'salon_reviews': 'Anmeldelser',
        'salon_directions': 'Veibeskrivelse',
        'salon_choose_time': 'Velg tid',
        'salon_confirm_booking': 'Bekreft bestilling',
        'salon_choose_provider': 'Velg utfører',
        'salon_book_now': 'Bestill nå',
        'salon_booking_confirmed': 'Bestilling bekreftet!',
        'salon_date_time': 'Dato & Tid',
        'explore_search_placeholder_2': 'Behandling eller salong...',
        'explore_filter_near_me': 'Nær meg',
        'explore_filter_available_today': 'Ledig i dag',
        'explore_filter_top_rating': 'Toppkarakter',
        'explore_filter_under_price': 'Under 500',
        'explore_filter_new': 'Nye utførere',
        'explore_clear_filters': 'Fjern alle',
        'explore_top_city_title': 'Topp i din by',
        'explore_top_city_desc': 'Høyest vurdert i ditt område',
        'explore_quick_times_title': 'Raske tider',
        'explore_quick_times_desc': 'Bestill raskt hos premium-utførere',
        'explore_new_providers_title': 'Nye utførere',
        'explore_new_providers_desc': 'Nylig tilkoblet Glowbook',
        'explore_search_results': 'Søkeresultater',
        'explore_all_providers': 'Alle utførere',
        'explore_sort_recommended': 'Anbefalt',
        'explore_sort_rating': 'Høyest vurdering',
        'explore_sort_price': 'Lavest pris',
        'footer_desc': 'Premium bookingplattform for skjønnhet & velvære. Kobler kunder med de beste utførerne.',
        'footer_quick_links': 'Hurtiglenker',
        'footer_explore': 'Utforsk',
        'footer_register': 'Registrer bedrift',
        'footer_legal': 'Juridisk',
        'footer_policies': 'Vilkår & Betingelser',
        'footer_privacy': 'Personvernerklæring (GDPR)',
        'footer_cookies': 'Informasjonskapsler',
        'footer_platform_online': 'Plattform Online',

        'popular_searches': 'Populære søk',
        'all_cities': 'Hele Norge',
        'premium_experience': 'Premium Booking Experience',
        'popular_categories': 'Populære Kategorier',
        'view_all': 'Vis alle',
        'more_categories': 'Flere Kategorier',
        'find_treatment_title': 'Finn din neste behandling nær deg',
        'find_treatment_desc': 'Vi finnes i hele Norden. Fra Oslo til Tromsø. Oppdag de beste salongene og frilanserne i din by.',
        'search_your_city': 'Søk i din by',
        'found_category': 'Vi fant kategorien:',
        'discover': 'Oppdag',
        'view_all_in': 'Vis alle innen',
        'nails': 'Negler',
        'lashes': 'Vipper',
        'massage': 'Massasje',
        'hair': 'Frisør',
        'facial': 'Ansiktsbehandling',
        'nav_bookings': 'Bestillinger',
        'nav_favorites': 'Favoritter',
        'nav_support': 'Kundeservice',
        'nav_search': 'Søk',
        'nav_giftcards': 'Gavekort',
        'nav_settings': 'Innstillinger',
        'nav_guides': 'Rådgivning',
        'nav_rewards': 'Rewards',
        'nav_inbox': 'Innboks',
        'nav_dashboard': 'Oversikt',
        'action_register_business': 'Registrer bedrift',
        'action_login': 'Logg inn',
        'my_pages': 'Mine sider',
        'location_title': 'Velg Sted',
        'location_search_placeholder': 'Søk kommune...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'En problemfri opplevelse for både kunder og utførere.\nIngen komplisert administrasjon, bare rent fokus på lidenskap.',
        'home_hero_cta_book': 'Bestill time',
        'home_hero_cta_register': 'Registrer bedrift',
        'home_categories_title': 'Våre Kategorier',
        'home_categories_subtitle': 'Håndplukkede eksperter innen skjønnhet og helse',
        'home_view_all': 'Vis alle',

        'cat_nails_name': 'Negler',
        'cat_nails_desc': 'Minimalistisk neglepleie & design',
        'cat_lashes_name': 'Vipper & Bryn',
        'cat_lashes_desc': 'Løft blikket med perfekt form',
        'cat_massage_name': 'Massasje',
        'cat_massage_desc': 'Dyp avslapning for sinnet',
        'cat_skin_name': 'Hudpleie',
        'cat_skin_desc': 'Fuktighetsgivende ansiktspleie & glød',
        'cat_hair_name': 'Hårpleie',
        'cat_hair_desc': 'Klipp, farge & styling',
        'cat_injection_name': 'Estetisk Injeksjon',
        'cat_injection_desc': 'Fillere, botox & hudforyngelse',
        'cat_tattoo_name': 'Tatovering',
        'cat_tattoo_desc': 'Kunst på hud, fra fine linjer til realisme',
        'cat_spa_name': 'Spa',
        'cat_spa_desc': 'Total avslapping & velvære',
        'cat_makeup_name': 'Sminke',
        'cat_makeup_desc': 'Profesjonell styling for enhver anledning',
        'cat_footcare_name': 'Fotpleie',
        'cat_footcare_desc': 'Medisinsk & kosmetisk fotpleie',
        'cat_chiro_name': 'Kiropraktikk',
        'cat_chiro_desc': 'Ledd- & muskelbehandling',
        'cat_naprapathy_name': 'Naprapati',
        'cat_naprapathy_desc': 'Manuell behandling av smerte',
        'cat_teeth_name': 'Tannbleking',
        'cat_teeth_desc': 'Profesjonelt hvitere smil',
        'cat_piercing_name': 'Piercing',
        'cat_piercing_desc': 'Trygg & stilren piercing',
        'cat_barber_name': 'Barberer',
        'cat_barber_desc': 'Klassisk herreklipp & barbering',
        'onboarding_title_1': 'Fortell om virksomheten din',
        'onboarding_title_2': 'Hvem står bak?',
        'onboarding_title_3': 'Velg din løsning',
        'onboarding_title_4': 'Glowbook Checkout',
        'onboarding_desc_1': 'Synlig for tusenvis av potensielle kunder.',
        'onboarding_desc_2': 'Dine opplysninger er trygge og vises ikke offentlig.',
        'onboarding_desc_3': 'Velg bindingstid for å senke din månedskostnad.',
        'onboarding_desc_4': 'Fullfør din bestilling sikkert via Stripe.',
        'onboarding_step_1': 'Virksomhet',
        'onboarding_step_2': 'Personlig',
        'onboarding_step_3': 'Abonnement',
        'onboarding_step_4': 'Betaling',
        'label_business_name': 'Virksomhetens Navn',
        'placeholder_business_name': 'F.eks. Glow Nails & Spa',
        'label_category': 'Kategori',
        'label_country': 'Land',
        'label_municipality': 'Kommune',
        'label_address': 'Adresse',
        'label_optional': '(Valgfritt)',
        'btn_next': 'Neste',
        'btn_back': 'Tilbake',
        'btn_complete_klarna': 'Fullfør kjøp via Stripe',
        'dash_welcome': 'Velkommen',
        'dash_overview': 'Oversikt',
        'dash_stat_bookings': 'Bestillinger i dag',
        'dash_stat_customers': 'Nye kunder',
        'dash_stat_revenue': 'Inntekter',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Kunderegister',
        'dash_nav_customers_desc': 'Se alle dine eksisterende kunder, historikk og kontaktinformasjon.',
        'dash_nav_services': 'Tjenester',
        'dash_nav_services_desc': 'Opprett nye tjenester, sett priser og tider, samt tilpass profilen din.',
        'dash_nav_finance': 'Økonomi',
        'dash_nav_finance_desc': 'Se inntekter fra Klarna og godkjenn betalinger gjort på stedet.',
        'dash_nav_settings': 'Innstillinger',
        'dash_nav_settings_desc': 'Administrer salonginformasjon, personlig info og medlemskap.',
        'dash_bookings_title': 'Bestillinger',
        'dash_new_booking': 'Ny bestilling',
        'dash_no_bookings': 'Ingen bestillinger ennå',
        'dash_no_bookings_desc': 'Det er ingen bestillinger registrert for denne uken.',
        'settings_title': 'Innstillinger',
        'settings_desc': 'Administrer din profil, dine opplysninger og ditt medlemskap.',
        'tab_profile': 'Profil & Konto',
        'tab_membership': 'Medlemskap',
        'tab_notifications': 'Varslinger',
        'settings_salon_title': 'Salonginformasjon',
        'settings_personal_title': 'Personlige Opplysninger',
        'label_first_name': 'Fornavn',
        'label_last_name': 'Etternavn',
        'label_email': 'Email',
        'btn_save_changes': 'Lagre alle endringer',
        'msg_changes_saved': 'Endringer lagret',
        'logout': 'Logg ut',
        'action_register': 'Opprett konto',
        'role_customer': 'Kunde',
        'role_provider': 'Utfører',
        'role_admin': 'Admin',
        'label_password': 'Passord',
        'action_login_prompt': 'Har du allerede en konto?',
        'msg_fill_all_fields': 'Vennligst fyll ut alle obligatoriske felt',
        'btn_change': 'Endre',
        'cal_today': 'I dag',
        'cal_week': 'Uke',
        'cal_add_slot': 'Legg ut tider',
        'cal_post_times': 'Legg ut tider i en ram',
        'cal_go_to': 'Gå til kalender',
        'btn_save_schedule': 'Lagre skjema',
        'explore_title': 'Oppdag skjønnhet',
        'salons_found': 'salonger funnet',
        'filter_placeholder': 'Filtrer resultater...',
        'found': 'Funnet',
        'no_salons_found': 'Ingen salonger funnet',
        'no_salons_desc': 'Prøv å endre søket ditt eller filtreringen.',
        'new_search_link': 'Gjør et nytt søk',
        'free_today': 'Ledig i dag',
        'view_profile': 'Vis profil',
        'from': 'Fra',
        'in': 'i',
        'action_manage_customers': 'Administrer kunder',
        'action_edit_menu': 'Rediger meny',
        'action_view_payouts': 'Se utbetalinger',
        'action_go_to_settings': 'Gå til innstillinger',
        'label_address_placeholder': 'Gateadresse',
        'label_main_category': 'Hovedkategori',
        'msg_contact_support_category': 'Kontakt support for å bytte bransjekategori.',
        'label_your_membership': 'Ditt medlemskap',
        'label_status_active': 'Aktivt',
        'label_months': 'måneder',
        'action_upgrade_plan': 'Oppgrader plan',
        'action_downgrade_cancel': 'Nedgrader / Avslutt',
        'desc_notifications_settings': 'Administrer varslingsinnstillingene dine.',
        'notif_new_bookings': 'Nye bestillinger',
        'notif_new_bookings_desc': 'Få varsel når en kunde bestiller en time',
        'notif_cancellations': 'Avbestillinger',
        'notif_cancellations_desc': 'Bli varslet når en bestilling avbestilles',
        'notif_reminders': 'Påminnelser',
        'notif_reminders_desc': 'Daglig sammendrag av kommende bestillinger',
        'notif_marketing': 'Markedsføring',
        'notif_marketing_desc': 'Nyheter og tilbud fra Glowbook',
        'notif_klarna_connecting': 'Kobler til Klarna...',
        'notif_klarna_processing': 'Behandler abonnement...',
        'notif_klarna_success': 'Betaling godkjent!',
        'notif_klarna_redirecting': 'Sender deg til dashbordet...',
        'notif_klarna_secure': 'Kryptert og sikker tilkobling',
        'action_cancel_purchase': 'Avbryt kjøp',
        'label_amount_to_pay': 'Beløp å betale nå',
        'msg_klarna_subscription': 'Håndteres som et abonnement via Klarna Payments',
        'label_select_category': 'Velg kategori',
        'msg_personal_data_warning': 'Disse opplysningene brukes kun til verifisering og fakturering. De vil ikke vises offentlig på profilen din.',
        'label_last_name_placeholder': 'Ditt etternavn',
        'label_first_name_placeholder': 'Ditt fornavn',
        'label_tier_start_desc': 'For solo techs i startfasen',
        'label_tier_pro_desc': 'For aktive beauty techs',
        'label_tier_studio_desc': 'For studioer og team',
        'label_most_popular': 'MEST POPULÆR',
        'label_total': 'Totalt',
        'msg_one_month_free': '1 måned gratis',
        'label_order_summary': 'Din bestilling',
        'label_subscription_length': 'Abonnementslengde',
        'msg_terms_agreement': 'Ved å gå videre bekrefter du at du godtar Glowbooks brukervilkår og personvernerklæring.',
        'label_renewal_automatic': 'Automatisk fornyelse',
        'action_manage_subscription': 'Administrer abonnement',
        'label_active': 'Aktiv',
        'action_select': 'Velg',
        'notif_payment_notice': 'Betalingsinformasjon',
        'msg_payment_one_time': 'Abonnementet ditt belastes som en engangskostnad via Klarna ved fornyelse.',
        'btn_save_subscription': 'Oppdater abonnement',
        'day_monday': 'Mandag',
        'day_tuesday': 'Tirsdag',
        'day_wednesday': 'Onsdag',
        'day_thursday': 'Torsdag',
        'day_friday': 'Fredag',
        'day_saturday': 'Lørdag',
        'day_sunday': 'Søndag',
        'msg_invalid_time_range': 'Sluttid må være etter starttid',
        'salon_appearance_title': 'Salongens utseende',
        'salon_appearance_desc': 'Last opp bilder som representerer virksomheten din.',
        'label_background_image': 'Bakgrunnsbilde (1200x400)',
        'action_change_background': 'Endre bakgrunn',
        'action_update': 'Oppdater',
        'action_create_service': 'Opprett ny tjeneste',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Forslag for din kategori',
        'label_service_name': 'Tjenestens navn',
        'label_price': 'Pris',
        'label_time': 'Tid',
        'label_description': 'Beskrivelse',
        'placeholder_description': 'Fortell kort om tjenesten...',
        'btn_save_service': 'Lagre tjeneste'
    },
    'Danska': {
        'search_title': 'Find din næste glow up',
        'search_subtitle': 'Søg efter behandlinger eller saloner i nærheden',
        'search_placeholder': 'Hvad leder du efter? (f.eks. negle, vipper...)',
        'search_in': 'Søg i',
        'municipality': 'Kommune',
        'search_button': 'Søg',
        'salon_services': 'Tjenester',
        'salon_about': 'Om os',
        'salon_reviews': 'Anmeldelser',
        'salon_directions': 'Rutevejledning',
        'salon_choose_time': 'Vælg tid',
        'salon_confirm_booking': 'Bekræft booking',
        'salon_choose_provider': 'Vælg behandler',
        'salon_book_now': 'Book nu',
        'salon_booking_confirmed': 'Booking bekræftet!',
        'salon_date_time': 'Dato & Tid',
        'explore_search_placeholder_2': 'Behandling eller salon...',
        'explore_filter_near_me': 'Nær mig',
        'explore_filter_available_today': 'Ledig i dag',
        'explore_filter_top_rating': 'Topbedømt',
        'explore_filter_under_price': 'Under 500',
        'explore_filter_new': 'Nye behandlere',
        'explore_clear_filters': 'Ryd alle',
        'explore_top_city_title': 'Top i din by',
        'explore_top_city_desc': 'Højest bedømt i dit område',
        'explore_quick_times_title': 'Hurtige tider',
        'explore_quick_times_desc': 'Book hurtigt hos premium-behandlere',
        'explore_new_providers_title': 'Nye behandlere',
        'explore_new_providers_desc': 'Nyligt tilsluttet Glowbook',
        'explore_search_results': 'Søgeresultater',
        'explore_all_providers': 'Alle behandlere',
        'explore_sort_recommended': 'Anbefalet',
        'explore_sort_rating': 'Højeste bedømmelse',
        'explore_sort_price': 'Laveste pris',
        'footer_desc': 'Premium bookingplatform for skønhed & velvære. Forbinder kunder med de bedste behandlere.',
        'footer_quick_links': 'Hurtige links',
        'footer_explore': 'Udforsk',
        'footer_register': 'Registrer virksomhed',
        'footer_legal': 'Juridisk',
        'footer_policies': 'Vilkår & Betingelser',
        'footer_privacy': 'Privatlivspolitik (GDPR)',
        'footer_cookies': 'Cookies',
        'footer_platform_online': 'Platform Online',

        'popular_searches': 'Populære søgninger',
        'all_cities': 'Hele Danmark',
        'premium_experience': 'Premium Booking Experience',
        'popular_categories': 'Populære Kategorier',
        'view_all': 'Vis alle',
        'more_categories': 'Flere Kategorier',
        'find_treatment_title': 'Find din næste behandling nær dig',
        'find_treatment_desc': 'Vi findes i hele Norden. Fra København til Skagen. Opdag de bedste saloner og freelancere i din by.',
        'search_your_city': 'Søg i din by',
        'found_category': 'Vi fandt kategorien:',
        'discover': 'Oplev',
        'view_all_in': 'Vis alle inden for',
        'nails': 'Negle',
        'lashes': 'Vipper',
        'massage': 'Massage',
        'hair': 'Frisør',
        'facial': 'Ansigtsbehandling',
        'nav_bookings': 'Bookinger',
        'nav_favorites': 'Favoritter',
        'nav_support': 'Kundeservice',
        'nav_search': 'Søg',
        'nav_giftcards': 'Gavekort',
        'nav_settings': 'Indstillinger',
        'nav_guides': 'Guides',
        'nav_rewards': 'Rewards',
        'nav_inbox': 'Indbakke',
        'nav_dashboard': 'Overblik',
        'action_register_business': 'Registrer virksomhed',
        'action_login': 'Log ind',
        'my_pages': 'Mine sider',
        'location_title': 'Vælg Sted',
        'location_search_placeholder': 'Søg kommune...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'En problemfri oplevelse for både kunder og udførere.\nIngen kompliceret administration, bare rent fokus på passion.',
        'home_hero_cta_book': 'Bestil tid',
        'home_hero_cta_register': 'Registrer virksomhed',
        'home_categories_title': 'Vores Kategorier',
        'home_categories_subtitle': 'Håndplukkede eksperter inden for skønhed og sundhed',
        'home_view_all': 'Vis alle',

        'cat_nails_name': 'Negle',
        'cat_nails_desc': 'Minimalistisk neglepleie & design',
        'cat_lashes_name': 'Vipper & Bryn',
        'cat_lashes_desc': 'Løft blikket med perfekt form',
        'cat_massage_name': 'Massage',
        'cat_massage_desc': 'Dyb afslapning for sindet',
        'cat_skin_name': 'Hudpleje',
        'cat_skin_desc': 'Fugtgivende ansigtspleje & glød',
        'cat_hair_name': 'Hårpleje',
        'cat_hair_desc': 'Klipning, farve & styling',
        'cat_injection_name': 'Æstetisk Injektion',
        'cat_injection_desc': 'Fillere, botox & hudforyngelse',
        'cat_tattoo_name': 'Tatovering',
        'cat_tattoo_desc': 'Kunst på hud, fra fine linjer til realisme',
        'cat_spa_name': 'Spa',
        'cat_spa_desc': 'Total afslapping & velvære',
        'cat_makeup_name': 'Makeup',
        'cat_makeup_desc': 'Professionel styling til enhver lejlighed',
        'cat_footcare_name': 'Fodpleje',
        'cat_footcare_desc': 'Medicinsk & kosmetisk fodpleje',
        'cat_chiro_name': 'Kiropraktik',
        'cat_chiro_desc': 'Led- & muskelbehandling',
        'cat_naprapathy_name': 'Naprapati',
        'cat_naprapathy_desc': 'Manuel behandling af smerte',
        'cat_teeth_name': 'Tandblegning',
        'cat_teeth_desc': 'Professionelt hvidere smil',
        'cat_piercing_name': 'Piercing',
        'cat_piercing_desc': 'Sikker & stilren piercing',
        'cat_barber_name': 'Barber',
        'cat_barber_desc': 'Klassisk herreklipning & barbering',
        'onboarding_title_1': 'Fortæl om din virksomhed',
        'onboarding_title_2': 'Hvem står bag?',
        'onboarding_title_3': 'Vælg din løsning',
        'onboarding_title_4': 'Glowbook Checkout',
        'onboarding_desc_1': 'Synlig for tusindvis af potentielle kunder.',
        'onboarding_desc_2': 'Dine oplysninger er sikre og vises ikke offentligt.',
        'onboarding_desc_3': 'Vælg bindingsperiode for at sænke din månedlige omkostning.',
        'onboarding_desc_4': 'Gennemfør din bestilling sikkert via Stripe.',
        'onboarding_step_1': 'Virksomhed',
        'onboarding_step_2': 'Personlig',
        'onboarding_step_3': 'Abonnement',
        'onboarding_step_4': 'Betaling',
        'label_business_name': 'Virksomhedens Navn',
        'placeholder_business_name': 'F.eks. Glow Nails & Spa',
        'label_category': 'Kategori',
        'label_country': 'Land',
        'label_municipality': 'Kommune',
        'label_address': 'Adresse',
        'label_optional': '(Valgfrit)',
        'btn_next': 'Næste',
        'btn_back': 'Tilbage',
        'btn_complete_klarna': 'Gennemfør køb via Stripe',
        'dash_welcome': 'Velkommen',
        'dash_overview': 'Overblik',
        'dash_stat_bookings': 'Bookinger i dag',
        'dash_stat_customers': 'Nye kunder',
        'dash_stat_revenue': 'Indtægter',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Kunderegister',
        'dash_nav_customers_desc': 'Se alle dine eksisterende kunder, historik og kontaktoplysninger.',
        'dash_nav_services': 'Tjenester',
        'dash_nav_services_desc': 'Opret nye tjenester, sæt priser og tider, samt tilpas din profil.',
        'dash_nav_finance': 'Økonomi',
        'dash_nav_finance_desc': 'Se indtægter från Klarna og godkend betalinger foretaget på stedet.',
        'dash_nav_settings': 'Indstillinger',
        'dash_nav_settings_desc': 'Administer salonoplysninger, personlig info og medlemskab.',
        'dash_bookings_title': 'Bookinger',
        'dash_new_booking': 'Ny booking',
        'dash_no_bookings': 'Ingen bookinger endnu',
        'dash_no_bookings_desc': 'Der er ingen bookinger registreret for denne uge.',
        'settings_title': 'Indstillinger',
        'settings_desc': 'Administrer din profil, dine oplysninger og ditt medlemskab.',
        'tab_profile': 'Profil & Konto',
        'tab_membership': 'Medlemskab',
        'tab_notifications': 'Beskeder',
        'settings_salon_title': 'Salonoplysninger',
        'settings_personal_title': 'Personlige Oplysninger',
        'label_first_name': 'Fornavn',
        'label_last_name': 'Efternavn',
        'label_email': 'Email',
        'btn_save_changes': 'Gem alle ændringer',
        'msg_changes_saved': 'Ändringer gemt',
        'logout': 'Log ud',
        'action_register': 'Opret konto',
        'role_customer': 'Kunde',
        'role_provider': 'Behandler',
        'role_admin': 'Admin',
        'label_password': 'Adgangskode',
        'action_login_prompt': 'Har du allerede en konto?',
        'msg_fill_all_fields': 'Venligst udfyld alle obligatoriske felter',
        'btn_change': 'Skift',
        'cal_today': 'I dag',
        'cal_week': 'Uge',
        'cal_add_slot': 'Læg tider ud',
        'cal_post_times': 'Læg tider ud i en ramme',
        'cal_go_to': 'Gå til kalender',
        'btn_save_schedule': 'Gem skema',
        'explore_title': 'Oplev skønhed',
        'salons_found': 'saloner fundet',
        'filter_placeholder': 'Filtrer resultater...',
        'found': 'Fundet',
        'no_salons_found': 'Ingen saloner fundet',
        'no_salons_desc': 'Prøv at ændre din søgning eller filtrering.',
        'new_search_link': 'Foretag en ny søgning',
        'free_today': 'Ledig i dag',
        'view_profile': 'Vis profil',
        'from': 'Fra',
        'in': 'i',
        'action_manage_customers': 'Administrer kunder',
        'action_edit_menu': 'Rediger menu',
        'action_view_payouts': 'Se udbetalinger',
        'action_go_to_settings': 'Gå til indstillinger',
        'label_address_placeholder': 'Gadeadresse',
        'label_main_category': 'Hovedkategori',
        'msg_contact_support_category': 'Kontakt support for at ændre branche-kategori.',
        'label_your_membership': 'Dit medlemskab',
        'label_status_active': 'Aktivt',
        'label_months': 'måneder',
        'action_upgrade_plan': 'Opgrader plan',
        'action_downgrade_cancel': 'Nedgrader / Opsig',
        'desc_notifications_settings': 'Administrer dine notifikationsindstillinger.',
        'notif_new_bookings': 'Nye bookinger',
        'notif_new_bookings_desc': 'Få besked når en kunde booker en tid',
        'notif_cancellations': 'Aflysninger',
        'notif_cancellations_desc': 'Bliv underrettet når en booking aflyses',
        'notif_reminders': 'Påmindelser',
        'notif_reminders_desc': 'Daglig oversigt over kommende bookinger',
        'notif_marketing': 'Markedsføring',
        'notif_marketing_desc': 'Nyheder og tilbud fra Glowbook',
        'notif_klarna_connecting': 'Forbinder til Klarna...',
        'notif_klarna_processing': 'Behandler abonnement...',
        'notif_klarna_success': 'Betaling godkendt!',
        'notif_klarna_redirecting': 'Sender dig til dit dashboard...',
        'notif_klarna_secure': 'Krypteret og sikker forbindelse',
        'action_cancel_purchase': 'Afbryd køb',
        'label_amount_to_pay': 'Beløb der skal betales nu',
        'msg_klarna_subscription': 'Håndteres som et abonnement via Klarna Payments',
        'label_select_category': 'Vælg kategori',
        'msg_personal_data_warning': 'Disse oplysninger bruges kun til verifikation og fakturering. De vil ikke blive vist offentligt på din profil.',
        'label_last_name_placeholder': 'Dit efternavn',
        'label_first_name_placeholder': 'Dit fornavn',
        'label_tier_start_desc': 'Til solo-teknikere i startfasen',
        'label_tier_pro_desc': 'Til aktive skønhedsteknikere',
        'label_tier_studio_desc': 'Til studier og teams',
        'label_most_popular': 'MEST POPULÆR',
        'label_total': 'Total',
        'msg_one_month_free': '1 måned gratis',
        'label_order_summary': 'Din bestilling',
        'label_subscription_length': 'Abonnementslængde',
        'msg_terms_agreement': 'Ved at gå videre bekræfter du, at du accepterer Glowbooks brugervilkår og privatlivspolitik.',
        'label_renewal_automatic': 'Automatisk fornyelse',
        'action_manage_subscription': 'Administrer abonnement',
        'label_active': 'Aktiv',
        'action_select': 'Vælg',
        'notif_payment_notice': 'Betalingsoplysninger',
        'msg_payment_one_time': 'Dit abonnement vil blive opkrævet som en engangsomkostning via Klarna ved fornyelse.',
        'btn_save_subscription': 'Opdater abonnement',
        'day_monday': 'Mandag',
        'day_tuesday': 'Tirsdag',
        'day_wednesday': 'Onsdag',
        'day_thursday': 'Torsdag',
        'day_friday': 'Fredag',
        'day_saturday': 'Lørdag',
        'day_sunday': 'Søndag',
        'msg_invalid_time_range': 'Sluttid skal være efter starttid',
        'salon_appearance_title': 'Salongens udseende',
        'salon_appearance_desc': 'Upload billeder, der repræsenterer din virksomhed.',
        'label_background_image': 'Baggrundsbillede (1200x400)',
        'action_change_background': 'Skift baggrund',
        'action_update': 'Opdater',
        'action_create_service': 'Opret ny tjeneste',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Forslag til din kategori',
        'label_service_name': 'Tjenestens navn',
        'label_price': 'Pris',
        'label_time': 'Tid',
        'label_description': 'Beskrivelse',
        'placeholder_description': 'Fortæl kort om tjenesten...',
        'btn_save_service': 'Gem tjeneste'
    },
    'Finska': {
        'search_title': 'Löydä seuraava glow up',
        'search_subtitle': 'Etsi hoitoja tai salonkeja läheltäsi',
        'search_placeholder': 'Mitä etsit? (esim. kynnet, ripset...)',
        'search_in': 'Hae kohteesta',
        'municipality': 'Kunta',
        'search_button': 'Hae',
        'salon_services': 'Palvelut',
        'salon_about': 'Meistä',
        'salon_reviews': 'Arvostelut',
        'salon_directions': 'Reittiohjeet',
        'salon_choose_time': 'Valitse aika',
        'salon_confirm_booking': 'Vahvista varaus',
        'salon_choose_provider': 'Valitse tekijä',
        'salon_book_now': 'Varaa nyt',
        'salon_booking_confirmed': 'Varaus vahvistettu!',
        'salon_date_time': 'Päivä & Aika',
        'explore_search_placeholder_2': 'Hoito tai salonki...',
        'explore_filter_near_me': 'Lähellä minua',
        'explore_filter_available_today': 'Vapaana tänään',
        'explore_filter_top_rating': 'Parhaat arviot',
        'explore_filter_under_price': 'Alle 500',
        'explore_filter_new': 'Uudet tekijät',
        'explore_clear_filters': 'Tyhjennä kaikki',
        'explore_top_city_title': 'Parhaat kaupungissasi',
        'explore_top_city_desc': 'Arvostetuimmat alueellasi',
        'explore_quick_times_title': 'Nopeat ajat',
        'explore_quick_times_desc': 'Varaa nopeasti premium-tekijöiltä',
        'explore_new_providers_title': 'Uudet tekijät',
        'explore_new_providers_desc': 'Äskettäin liittyneet Glowbookiin',
        'explore_search_results': 'Hakutulokset',
        'explore_all_providers': 'Kaikki tekijät',
        'explore_sort_recommended': 'Suositellut',
        'explore_sort_rating': 'Korkein arvio',
        'explore_sort_price': 'Alin hinta',
        'footer_desc': 'Premium varausalusta kauneudelle & hyvinvoinnille. Yhdistää asiakkaat parhaiden tekijöiden kanssa.',
        'footer_quick_links': 'Pikalinkit',
        'footer_explore': 'Tutustu',
        'footer_register': 'Rekisteröi yritys',
        'footer_legal': 'Oikeudellinen',
        'footer_policies': 'Käyttöehdot',
        'footer_privacy': 'Tietosuojaseloste (GDPR)',
        'footer_cookies': 'Evästeet',
        'footer_platform_online': 'Alusta Online',
        'all_cities': 'Koko Suomi',
        'premium_experience': 'Premium Booking Experience',
        'popular_categories': 'Suositut Kategoriat',
        'view_all': 'Näytä kaikki',
        'more_categories': 'Lisää Kategorioita',
        'find_treatment_title': 'Löydä seuraava hoitosi läheltäsi',
        'find_treatment_desc': 'Olemme kaikkialla Pohjoismaissa. Tuki- ja Helsingistä Tukholmaan. Löydä kaupunkisi parhaat salongit ja freelancerit.',
        'search_your_city': 'Hae kaupungistasi',
        'popular_searches': 'Suositut haut',
        'found_category': 'Löysimme kategorian:',
        'discover': 'Löydä',
        'view_all_in': 'Näytä kaikki osastolla',
        'nails': 'Kynnet',
        'lashes': 'Ripset',
        'massage': 'Hieronta',
        'hair': 'Kampaaja',
        'facial': 'Kasvohoito',
        'nav_bookings': 'Varaukset',
        'nav_favorites': 'Suosikit',
        'nav_support': 'Asiakaspalvelu',
        'nav_search': 'Hae',
        'nav_giftcards': 'Lahjakortti',
        'nav_settings': 'Asetukset',
        'nav_guides': 'Oppaat',
        'nav_rewards': 'Palkinnot',
        'nav_inbox': 'Saapuneet',
        'action_register_business': 'Rekisteröi yritys',
        'action_login': 'Kirjaudu sisään',
        'my_pages': 'Omat sivut',
        'location_title': 'Valitse Sijainti',
        'location_search_placeholder': 'Hae kuntaa...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'Vaivaton kokemus sekä asiakkaille että tekijöille.\nEi monimutkaista hallintoa, vain puhdas keskittyminen intohimoon.',
        'home_hero_cta_book': 'Varaa aika',
        'home_hero_cta_register': 'Rekisteröi yritys',
        'home_categories_title': 'Meidän Kategoriamme',
        'home_categories_subtitle': 'Käsinpoimitut kauneuden ja terveyden asiantuntijat',
        'home_view_all': 'Näytä kaikki',
        'cat_nails_name': 'Kynnet',
        'cat_nails_desc': 'Minimalistinen kynsienhoito & muotoilu',
        'cat_lashes_name': 'Ripset & Kulmat',
        'cat_lashes_desc': 'Nosta katsettasi täydellisellä muodolla',
        'cat_massage_name': 'Hieronta',
        'cat_massage_desc': 'Syvä rentoutus mielelle',
        'cat_skin_name': 'Ihonhoito',
        'cat_skin_desc': 'Kosteuttava kasvojenhoito & hehku',
        'cat_hair_name': 'Hiustenhoito',
        'cat_hair_desc': 'Leikkaus, väri & muotoilu',
        'cat_injection_name': 'Esteettinen Injektio',
        'cat_injection_desc': 'Täyteaineet, botox & ihon nuorennus',
        'cat_tattoo_name': 'Tatuointi',
        'cat_tattoo_desc': 'Taidetta iholle, ohuista linjoista realismiin',
        'cat_spa_name': 'Kylpylä',
        'cat_spa_desc': 'Täydellinen rentoutuminen & hyvinvointi',
        'cat_makeup_name': 'Meikki',
        'cat_makeup_desc': 'Ammattimainen tyyli joka tilaisuuteen',
        'cat_footcare_name': 'Jalkahoito',
        'cat_footcare_desc': 'Lääketieteellinen & kosmeettinen jalkahoito',
        'cat_chiro_name': 'Kiropraktiikka',
        'cat_chiro_desc': 'Nivel- & lihashoito',
        'cat_naprapathy_name': 'Naprapatia',
        'cat_naprapathy_desc': 'Manuaalinen kivunhoito',
        'cat_teeth_name': 'Hampaiden Valkaisu',
        'cat_teeth_desc': 'Ammattimainen valkaiseminen',
        'cat_piercing_name': 'Lävistys',
        'cat_piercing_desc': 'Turvallinen & tyylikäs lävistys',
        'cat_barber_name': 'Parturi',
        'cat_barber_desc': 'Klassinen miesten leikkaus & parranajo',
        'onboarding_title_1': 'Kerro yrityksestäsi',
        'onboarding_title_2': 'Kuka on takana?',
        'onboarding_title_3': 'Valitse ratkaisusi',
        'onboarding_title_4': 'Glowbook Checkout',
        'onboarding_desc_1': 'Näkyvissä tuhansille potentiaalisille asiakkaille.',
        'onboarding_desc_2': 'Tietosi ovat turvassa eivätkä näy julkisesti.',
        'onboarding_desc_3': 'Valitse sitoutumisaika alentaaksesi kuukausikustannuksiasi.',
        'onboarding_desc_4': 'Viimeistele tilauksesi turvallisesti Stripellä.',
        'onboarding_step_1': 'Yritys',
        'onboarding_step_2': 'Henkilökohtainen',
        'onboarding_step_3': 'Tilaus',
        'onboarding_step_4': 'Maksu',
        'label_business_name': 'Yrityksen Nimi',
        'placeholder_business_name': 'Esim. Glow Nails & Spa',
        'label_category': 'Kategori',
        'label_country': 'Maa',
        'label_municipality': 'Kunta',
        'label_address': 'Osoite',
        'label_optional': '(Valinnainen)',
        'btn_next': 'Seuraava',
        'btn_back': 'Takaisin',
        'btn_complete_klarna': 'Viimeistele osto Stripellä',
        'dash_welcome': 'Tervetuloa',
        'dash_overview': 'Tässä on yleiskatsaus yrityksestäsi.',
        'dash_stat_bookings': 'Varaukset tänään',
        'dash_stat_customers': 'Uudet asiakkaat',
        'dash_stat_revenue': 'Tulot',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Asiakasrekisteri',
        'dash_nav_customers_desc': 'Katso kaikki olemassa olevat asiakkaasi, historia ja yhteystiedot.',
        'dash_nav_services': 'Palvelut',
        'dash_nav_services_desc': 'Luo uusia palveluita, aseta hintoja ja aikoja sekä muokkaa profiiliasi.',
        'dash_nav_finance': 'Talous',
        'dash_nav_finance_desc': 'Katso tulot Klarnasta ja hyväksy paikan päällä tehdyt maksut.',
        'dash_nav_settings': 'Asetukset',
        'dash_nav_settings_desc': 'Hallitse salongin tietoja, henkilökohtaisia tietoja ja jäsenyyttä.',
        'dash_bookings_title': 'Varaukset',
        'dash_new_booking': 'Uusi varaus',
        'dash_no_bookings': 'Ei vielä varauksia',
        'dash_no_bookings_desc': 'Tälle viikolle ei ole rekisteröity varauksia.',
        'settings_title': 'Asetukset',
        'settings_desc': 'Hallitse profiiliasi, tietojasi ja jäsenyyttäsi.',
        'tab_profile': 'Profiili & Tili',
        'tab_membership': 'Jäsenyys',
        'tab_notifications': 'Ilmoitukset',
        'settings_salon_title': 'Salongin Tiedot',
        'settings_personal_title': 'Henkilötiedot',
        'label_first_name': 'Etunimi',
        'label_last_name': 'Sukunimi',
        'label_email': 'Sähköposti',
        'btn_save_changes': 'Tallenna kaikki muutokset',
        'msg_changes_saved': 'Muutokset tallennettu',
        'logout': 'Kirjaudu ulos',
        'action_register': 'Luo tili',
        'role_customer': 'Asiakas',
        'role_provider': 'Palveluntarjoaja',
        'role_admin': 'Ylläpitäjä',
        'label_password': 'Salasana',
        'action_login_prompt': 'Onko sinulla jo tili?',
        'msg_fill_all_fields': 'Täytä kaikki pakolliset kentät',
        'btn_change': 'Muuta',
        'cal_today': 'Tänään',
        'cal_week': 'Viikko',
        'cal_add_slot': 'Lisää aikoja',
        'cal_post_times': 'Aseta ajat kehykseen',
        'cal_go_to': 'Siirry kalenteriin',
        'btn_save_schedule': 'Tallenna aikataulu',
        'explore_title': 'Löydä kauneutta',
        'salons_found': 'salonkia löytyi',
        'filter_placeholder': 'Suodata tuloksia...',
        'found': 'Löytyi',
        'no_salons_found': 'Salonkia ei löytynyt',
        'no_salons_desc': 'Kokeile muuttaa hakuasi tai suodatustasi.',
        'new_search_link': 'Tee uusi haku',
        'free_today': 'Vapaana tänään',
        'view_profile': 'Katso profiili',
        'from': 'Alkaen',
        'in': 'kohteessa',
        'action_manage_customers': 'Hallinnoi asiakkaita',
        'action_edit_menu': 'Muokkaa valikkoa',
        'action_view_payouts': 'Näytä maksut',
        'action_go_to_settings': 'Siirry asetuksiin',
        'label_address_placeholder': 'Katuosoite',
        'label_main_category': 'Pääkategoria',
        'msg_contact_support_category': 'Ota yhteyttä tukeen vaihtaaksesi toimialaluokkaa.',
        'label_your_membership': 'Jäsenyytesi',
        'label_status_active': 'Aktiivinen',
        'label_months': 'kuukautta',
        'action_upgrade_plan': 'Päivitä tilaus',
        'action_downgrade_cancel': 'Laske tasoa / Peruuta',
        'desc_notifications_settings': 'Hallitse ilmoitusasetuksiasi.',
        'notif_new_bookings': 'Uudet varaukset',
        'notif_new_bookings_desc': 'Saa ilmoitus, kun asiakas varaa ajan',
        'notif_cancellations': 'Peruutukset',
        'notif_cancellations_desc': 'Saa ilmoitus, kun varaus peruutetaan',
        'notif_reminders': 'Muistutukset',
        'notif_reminders_desc': 'Päivittäinen yhteenveto tulevista varauksista',
        'notif_marketing': 'Markkinointi',
        'notif_marketing_desc': 'Uutisia ja tarjouksia Glowbookilta',
        'notif_klarna_connecting': 'Yhdistetään Klarnaan...',
        'notif_klarna_processing': 'Käsitellään tilausta...',
        'notif_klarna_success': 'Maksu hyväksytty!',
        'notif_klarna_redirecting': 'Ohjataan hallintapaneeliin...',
        'notif_klarna_secure': 'Salattu ja turvallinen yhteys',
        'action_cancel_purchase': 'Peruuta osto',
        'label_amount_to_pay': 'Maksettava summa nyt',
        'msg_klarna_subscription': 'Käsitellään tilauksena Klarna Paymentsin kautta',
        'label_select_category': 'Valitse kategoria',
        'msg_personal_data_warning': 'Näitä tietoja käytetään vain varmistukseen ja laskutukseen. Niitä ei näytetä julkisesti profiilissasi.',
        'label_last_name_placeholder': 'Sukunimesi',
        'label_first_name_placeholder': 'Etunimesi',
        'label_tier_start_desc': 'Yksinyrittäjille aloitusvaiheessa',
        'label_tier_pro_desc': 'Aktiivisille kauneuden ammattilaisille',
        'label_tier_studio_desc': 'Studioille ja tiimeille',
        'label_most_popular': 'SUOSITUIN',
        'label_total': 'Yhteensä',
        'msg_one_month_free': '1 kuukausi ilmaiseksi',
        'label_order_summary': 'Tilauksesi',
        'label_subscription_length': 'Tilauksen kesto',
        'msg_terms_agreement': 'Jatkamalla vahvistat hyväksyväsi Glowbookin käyttöehdot ja tietosuojakäytännön.',
        'label_renewal_automatic': 'Automaattinen uusiminen',
        'action_manage_subscription': 'Hallitse tilausta',
        'label_active': 'Aktiivinen',
        'action_select': 'Valitse',
        'notif_payment_notice': 'Maksutiedot',
        'msg_payment_one_time': 'Tilauksesi veloitetaan kertamaksuna Klarnan kautta uusittaessa.',
        'btn_save_subscription': 'Päivitä tilaus',
        'day_monday': 'Maanantai',
        'day_tuesday': 'Tiistai',
        'day_wednesday': 'Keskiviikko',
        'day_thursday': 'Torstai',
        'day_friday': 'Perjantai',
        'day_saturday': 'Lauantai',
        'day_sunday': 'Sunnuntai',
        'msg_invalid_time_range': 'Päättymisajan on oltava aloitusajan jälkeen',
        'salon_appearance_title': 'Salongin ulkoasu',
        'salon_appearance_desc': 'Lataa kuvia, jotka edustavat yritystäsi.',
        'label_background_image': 'Taustakuva (1200x400)',
        'action_change_background': 'Vaihda taustakuva',
        'action_update': 'Päivitä',
        'action_create_service': 'Luo uusi palvelu',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Ehdotuksia kategoriallesi',
        'label_service_name': 'Palvelun nimi',
        'label_price': 'Hinta',
        'label_time': 'Aika',
        'label_description': 'Kuvaus',
        'placeholder_description': 'Kerro lyhyesti palvelusta...',
        'btn_save_service': 'Tallenna palvelu'
    },
    'Isländska': {
        'search_title': 'Finndu næsta glow up',
        'search_subtitle': 'Leita að meðferðum eða stofum í nágrenninu',
        'search_placeholder': 'Hvað ertu að leita að? (t.ex. neglur, augnhár...)',
        'search_in': 'Leita í',
        'municipality': 'Sveitarfélag',
        'search_button': 'Leita',
        'salon_services': 'Þjónustur',
        'salon_about': 'Um okkur',
        'salon_reviews': 'Umsagnir',
        'salon_directions': 'Leiðbeiningar',
        'salon_choose_time': 'Veldu tíma',
        'salon_confirm_booking': 'Staðfesta bókun',
        'salon_choose_provider': 'Veldu fagaðila',
        'salon_book_now': 'Bóka núna',
        'salon_booking_confirmed': 'Bókun staðfest!',
        'salon_date_time': 'Dagsetning & Tími',
        'explore_search_placeholder_2': 'Meðferð eða stofa...',
        'explore_filter_near_me': 'Nálægt mér',
        'explore_filter_available_today': 'Laust í dag',
        'explore_filter_top_rating': 'Hæsta einkunn',
        'explore_filter_under_price': 'Undir 500',
        'explore_filter_new': 'Nýir fagaðilar',
        'explore_clear_filters': 'Hreinsa allt',
        'explore_top_city_title': 'Topp í þínum bæ',
        'explore_top_city_desc': 'Vinsælast í þínu nágrenni',
        'explore_quick_times_title': 'Fljótlegir tímar',
        'explore_quick_times_desc': 'Bókaðu fljótt hjá premium fagaðilum',
        'explore_new_providers_title': 'Nýir fagaðilar',
        'explore_new_providers_desc': 'Nýskráðir á Glowbook',
        'explore_search_results': 'Leitarniðurstöður',
        'explore_all_providers': 'Allir fagaðilar',
        'explore_sort_recommended': 'Mælt með',
        'explore_sort_rating': 'Hæsta einkunn',
        'explore_sort_price': 'Lægsta verð',
        'footer_desc': 'Premium bókunarvettvangur fyrir fegurð & vellíðan. Tengir viðskiptavini við bestu fagaðilana.',
        'footer_quick_links': 'Flýtivísar',
        'footer_explore': 'Kanna',
        'footer_register': 'Skrá fyrirtæki',
        'footer_legal': 'Lagalegt',
        'footer_policies': 'Skilmálar',
        'footer_privacy': 'Persónuvernd (GDPR)',
        'footer_cookies': 'Vafrakökur',
        'footer_platform_online': 'Pallur Online',
        'all_cities': 'Allt Ísland',
        'premium_experience': 'Premium Booking Experience',
        'popular_categories': 'Vinsælir Flokkar',
        'view_all': 'Sjá allt',
        'more_categories': 'Fleiri Flokkar',
        'find_treatment_title': 'Finndu næstu meðferð nálægt þér',
        'find_treatment_desc': 'Við erum um öll Norðurlönd. Frá Reykjavík til Kaupmannahafnar. Uppgötvaðu bestu stofurnar og sjálfstætt starfandi fólkið í þínum bæ.',
        'search_your_city': 'Leitaðu í þínum bæ',
        'popular_searches': 'Vinsælar leitir',
        'found_category': 'Við fundum flokkinn:',
        'discover': 'Uppgötva',
        'view_all_in': 'Sjá allt í',
        'nails': 'Neglur',
        'lashes': 'Augnhár',
        'massage': 'Nudd',
        'hair': 'Hárgreiðsla',
        'facial': 'Andlitsmeðferð',
        'nav_bookings': 'Bókanir',
        'nav_favorites': 'Uppáhalds',
        'nav_support': 'Þjónustuver',
        'nav_search': 'Leita',
        'nav_giftcards': 'Gjafabréf',
        'nav_settings': 'Stillingar',
        'nav_guides': 'Leiðbeiningar',
        'nav_rewards': 'Verðlaun',
        'nav_inbox': 'Pósthólf',
        'action_register_business': 'Skrá fyrirtæki',
        'action_login': 'Skrá inn',
        'my_pages': 'Mínar síður',
        'location_title': 'Veldu Staðsetningu',
        'location_search_placeholder': 'Leita að sveitarfélagi...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'Vandræðalaus upplifun fyrir bæði viðskiptavini og fagaðila.\nEngin flókin stjórnsýsla, aðeins hrein áhersla á ástríðu.',
        'home_hero_cta_book': 'Bóka tíma',
        'home_hero_cta_register': 'Skrá fyrirtæki',
        'home_categories_title': 'Okkar Flokkar',
        'home_categories_subtitle': 'Handvaldir sérfræðingar í fegurð og heilsu',
        'home_view_all': 'Sjá allt',
        'cat_nails_name': 'Neglur',
        'cat_nails_desc': 'Lágmarks naglaumhirða & hönnun',
        'cat_lashes_name': 'Augnhár & Brýn',
        'cat_lashes_desc': 'Lyftu augnaráðinu med fullkominni lögun',
        'cat_massage_name': 'Nudd',
        'cat_massage_desc': 'Djúp slökun fyrir hugann',
        'cat_skin_name': 'Húðumhirða',
        'cat_skin_desc': 'Rakagefandi andlitsumhirða & ljómi',
        'cat_hair_name': 'Hárgreiðsla',
        'cat_hair_desc': 'Klipping, litun & stíll',
        'cat_injection_name': 'Fagurfræðileg Inndæling',
        'cat_injection_desc': 'Fyllingar, botox & húðendurnýjun',
        'cat_tattoo_name': 'Húðflúr',
        'cat_tattoo_desc': 'List á húð, frá fínum línum til raunsæis',
        'cat_spa_name': 'Heilsulindir',
        'cat_spa_desc': 'Algjör slökun & vellíðan',
        'cat_makeup_name': 'Förðun',
        'cat_makeup_desc': 'Fagleg stíll fyrir hvert tilefni',
        'cat_footcare_name': 'Fótaaðgerð',
        'cat_footcare_desc': 'Læknisfræðileg & snyrtifræðileg fótumhirða',
        'cat_chiro_name': 'Hryggjarmeðferð',
        'cat_chiro_desc': 'Lið- & vöðvameðferð',
        'cat_naprapathy_name': 'Naprapatía',
        'cat_naprapathy_desc': 'Handvirk meðferð á verkjum',
        'cat_teeth_name': 'Tannhvíttur',
        'cat_teeth_desc': 'Fagleg hvítari bros',
        'cat_piercing_name': 'Gatanir',
        'cat_piercing_desc': 'Örugg & stílhrein gatan',
        'cat_barber_name': 'Rakari',
        'cat_barber_desc': 'Klassísk herraklipping & rakning',
        'onboarding_title_1': 'Segðu okkur frá fyrirtækinu þínu',
        'onboarding_title_2': 'Hver stendur að baki?',
        'onboarding_title_3': 'Veldu þína lausn',
        'onboarding_title_4': 'Klarna Checkout',
        'onboarding_desc_1': 'Sýnilegt þúsundum hugsanlegra viðskiptavina.',
        'onboarding_desc_2': 'Upplýsingar þínar eru öruggar og ekki sýnilegar opinberlega.',
        'onboarding_desc_3': 'Veldu bindingartíma til að lækka mánaðarkostnaðinn þinn.',
        'onboarding_desc_4': 'Ljúktu pöntun þinni á öruggan hátt med Klarna.',
        'onboarding_step_1': 'Fyrirtæki',
        'onboarding_step_2': 'Persónulegt',
        'onboarding_step_3': 'Áskrifta',
        'onboarding_step_4': 'Greiðsla',
        'label_business_name': 'Nafn Fyrirtækis',
        'placeholder_business_name': 'T.ex. Glow Nails & Spa',
        'label_category': 'Flokkur',
        'label_country': 'Land',
        'label_municipality': 'Sveitarfélag',
        'label_address': 'Heimilisfang',
        'label_optional': '(Valfrjálst)',
        'btn_next': 'Næst',
        'btn_back': 'Til baka',
        'btn_complete_klarna': 'Ljúka kaupum med Klarna.',
        'dash_welcome': 'Velkomin',
        'dash_overview': 'Hér er yfirlit yfir fyrirtækið þitt.',
        'dash_stat_bookings': 'Bókanir í dag',
        'dash_stat_customers': 'Nýir viðskiptavinir',
        'dash_stat_revenue': 'Tekjur',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Viðskiptavinaskrá',
        'dash_nav_customers_desc': 'Sjá alla núverandi viðskiptavini þína, sögu og samskiptaupplýsingar.',
        'dash_nav_services': 'Þjónusta',
        'dash_nav_services_desc': 'Búa til nýja þjónustu, setja verð og tíma, og sérsníða prófílinn þinn.',
        'dash_nav_finance': 'Fjármál',
        'dash_nav_finance_desc': 'Sjá tekjur frá Klarna og samþykkja greiðslur gerðar á staðnum.',
        'dash_nav_settings': 'Stillingar',
        'dash_nav_settings_desc': 'Stjórna upplýsingum um stofu, persónulegum upplýsingum og aðild.',
        'dash_bookings_title': 'Bókanir',
        'dash_new_booking': 'Ný bókun',
        'dash_no_bookings': 'Engar bókanir ennþá',
        'dash_no_bookings_desc': 'Það eru engar bókanir skráðar í þessari viku.',
        'settings_title': 'Stillingar',
        'settings_desc': 'Stjórna prófílnum þínum, upplýsingum þínum og aðild þinni.',
        'tab_profile': 'Prófíll & Reikningur',
        'tab_membership': 'Aðild',
        'tab_notifications': 'Tilkynningar',
        'settings_salon_title': 'Upplýsingar um Stofu',
        'settings_personal_title': 'Persónulegar Upplýsingar',
        'label_first_name': 'Fornafn',
        'label_last_name': 'Eftirnafn',
        'label_email': 'Email',
        'btn_save_changes': 'Vista allar breytingar',
        'msg_changes_saved': 'Breytingar vistaðar',
        'logout': 'Skrá út',
        'action_register': 'Stofna reikning',
        'role_customer': 'Viðskiptavinur',
        'role_provider': 'Þjónustuaðili',
        'role_admin': 'Stjórnandi',
        'label_password': 'Lykilorð',
        'action_login_prompt': 'Ertu þegar med reikning?',
        'msg_fill_all_fields': 'Vinsamlegast fylltu út alla nauðsynlega reiti',
        'btn_change': 'Breyta',
        'cal_today': 'Í dag',
        'cal_week': 'Vika',
        'cal_add_slot': 'Bæta við tímum',
        'cal_post_times': 'Setja tíma í ramma',
        'cal_go_to': 'Fara í dagatal',
        'btn_save_schedule': 'Vista stundatöflu',
        'explore_title': 'Uppgötvaðu fegurð',
        'salons_found': 'stofur fundnar',
        'filter_placeholder': 'Sía niðurstður...',
        'found': 'Fannst',
        'no_salons_found': 'Engar stofur fundust',
        'no_salons_desc': 'Prófaðu að breyta leitinni eða síunni.',
        'new_search_link': 'Gera nýja leit',
        'free_today': 'Laust í dag',
        'view_profile': 'Skoða prófíl',
        'from': 'Frá',
        'in': 'í',
        'action_manage_customers': 'Sjá viðskiptavini',
        'action_edit_menu': 'Breyta matseðli',
        'action_view_payouts': 'Sjá úthlutanir',
        'action_go_to_settings': 'Fara í stillingar',
        'label_address_placeholder': 'Heimilisfang',
        'label_main_category': 'Aðalflokkur',
        'msg_contact_support_category': 'Hafðu samband við aðstoð til að breyta atvinnuflokki.',
        'label_your_membership': 'Aðild þín',
        'label_status_active': 'Virk',
        'label_months': 'mánuðir',
        'action_upgrade_plan': 'Uppfæra áskrift',
        'action_downgrade_cancel': 'Lækka áskrift / Hætta við',
        'desc_notifications_settings': 'Stjórnaðu tilkynningastillingum þínum.',
        'notif_new_bookings': 'Nýjar bókanir',
        'notif_new_bookings_desc': 'Få tilkynningu þegar viðskiptavinur bókar tíma',
        'notif_cancellations': 'Afpantanir',
        'notif_cancellations_desc': 'Fá tilkynningu þegar bókun er afpöntuð',
        'notif_reminders': 'Áminningar',
        'notif_reminders_desc': 'Daglegt yfirlit yfir komandi bókanir',
        'notif_marketing': 'Markaðssetning',
        'notif_marketing_desc': 'Fréttir og tilboð frá Glowbook',
        'notif_klarna_connecting': 'Tengist Klarna...',
        'notif_klarna_processing': 'Vinnur úr áskrift...',
        'notif_klarna_success': 'Greiðsla samþykkt!',
        'notif_klarna_redirecting': 'Sendir þig á stjórnborðið...',
        'notif_klarna_secure': 'Dulkóðuð og örugg tenging',
        'action_cancel_purchase': 'Hætta við kaup',
        'label_amount_to_pay': 'Upphæð til greiðslu núna',
        'msg_klarna_subscription': 'Meðhöndlað sem áskrift í gegnum Klarna Payments',
        'label_select_category': 'Veldu flokk',
        'msg_personal_data_warning': 'Þessar upplýsingar eru eingöngu notaðar til staðfestingar og reikningagerðar. Þær verða ekki birtar opinberlega á prófílnum þínum.',
        'label_last_name_placeholder': 'Eftirnafnið þitt',
        'label_first_name_placeholder': 'Fornafnið þitt',
        'label_tier_start_desc': 'Fyrir sjálfstætt starfandi í upphafi',
        'label_tier_pro_desc': 'Fyrir virka fagaðila í fegurðarþjónustu',
        'label_tier_studio_desc': 'Fyrir stofur og teymi',
        'label_most_popular': 'VINSÆLAST',
        'label_total': 'Samtals',
        'msg_one_month_free': '1 mánuður ókeypis',
        'label_order_summary': 'Pöntunin þín',
        'label_subscription_length': 'Lengd áskriftar',
        'msg_terms_agreement': 'Með því að halda áfram staðfestir þú að þú samþykkir notkunarskilmála og persónuverndarstefnu Glowbook.',
        'label_renewal_automatic': 'Sjálfvirk endurnýjun',
        'action_manage_subscription': 'Sýsla með áskrift',
        'label_active': 'Virkt',
        'action_select': 'Velja',
        'notif_payment_notice': 'Greiðsluupplýsingar',
        'msg_payment_one_time': 'Áskriftin þín verður gjaldfærð sem eingreiðsla í gegnum Klarna við endurnýjun.',
        'btn_save_subscription': 'Uppfæra áskrift',
        'day_monday': 'Mánudagur',
        'day_tuesday': 'Þriðjudagur',
        'day_wednesday': 'Miðvikudagur',
        'day_thursday': 'Fimmtudagur',
        'day_friday': 'Föstudagur',
        'day_saturday': 'Laugardagur',
        'day_sunday': 'Sunnudagur',
        'msg_invalid_time_range': 'Lokatími verður að vera eftir upphafstíma',
        'salon_appearance_title': 'Útlit stofu',
        'salon_appearance_desc': 'Hladdu upp myndum sem tákna fyrirtækið þitt.',
        'label_background_image': 'Bakgrunnsmynd (1200x400)',
        'action_change_background': 'Breyta bakgrunni',
        'action_update': 'Uppfæra',
        'action_create_service': 'Búa til nýja þjónustu',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Tillögur fyrir þinn flokk',
        'label_service_name': 'Nafn þjónustu',
        'label_price': 'Verð',
        'label_time': 'Tími',
        'label_description': 'Lýsing',
        'placeholder_description': 'Segðu stuttlega frá þjónustunni...',
        'btn_save_service': 'Vista þjónustu'
    },
    'English': {
        'search_title': 'Find your next glow up',
        'search_subtitle': 'Search for treatments or salons near you',
        'search_placeholder': 'What are you looking for? (e.g. nails, lashes...)',
        'search_in': 'Search in',
        'municipality': 'Municipality',
        'search_button': 'Search',
        'salon_services': 'Services',
        'salon_about': 'About Us',
        'salon_reviews': 'Reviews',
        'salon_directions': 'Directions',
        'salon_choose_time': 'Choose time',
        'salon_confirm_booking': 'Confirm booking',
        'salon_choose_provider': 'Choose practitioner',
        'salon_book_now': 'Book now',
        'salon_booking_confirmed': 'Booking confirmed!',
        'salon_date_time': 'Date & Time',
        'explore_search_placeholder_2': 'Treatment or salon...',
        'explore_filter_near_me': 'Near me',
        'explore_filter_available_today': 'Available today',
        'explore_filter_top_rating': 'Top rated',
        'explore_filter_under_price': 'Under 500',
        'explore_filter_new': 'New providers',
        'explore_clear_filters': 'Clear all',
        'explore_top_city_title': 'Top in your city',
        'explore_top_city_desc': 'Highest rated in your area',
        'explore_quick_times_title': 'Quick times',
        'explore_quick_times_desc': 'Book quickly with premium providers',
        'explore_new_providers_title': 'New providers',
        'explore_new_providers_desc': 'Recently joined Glowbook',
        'explore_search_results': 'Search results',
        'explore_all_providers': 'All providers',
        'explore_sort_recommended': 'Recommended',
        'explore_sort_rating': 'Highest rating',
        'explore_sort_price': 'Lowest price',
        'footer_desc': 'Premium booking platform for beauty & wellness. Connecting clients with the best professionals.',
        'footer_quick_links': 'Quick Links',
        'footer_explore': 'Explore',
        'footer_register': 'Register Business',
        'footer_legal': 'Legal',
        'footer_policies': 'Terms & Conditions',
        'footer_privacy': 'Privacy Policy (GDPR)',
        'footer_cookies': 'Cookies',
        'footer_platform_online': 'Platform Online',

        'salons_found': 'salons found',
        'no_salons_found': 'No salons found',
        'no_salons_desc': 'Try adjusting your filters or search for something else.',
        'new_search_link': 'New Search',

        'popular_searches': 'Popular searches',
        'all_cities': 'All cities',
        'premium_experience': 'Premium Booking Experience',
        'popular_categories': 'Popular Categories',
        'view_all': 'View all',
        'more_categories': 'More Categories',
        'find_treatment_title': 'Find your next treatment near you',
        'find_treatment_desc': 'We are across the Nordics. From London to Stockholm. Discover the best salons and freelancers in your city.',
        'search_your_city': 'Search in your city',
        'found_category': 'We found the category:',
        'discover': 'Discover',
        'view_all_in': 'View all in',
        'nails': 'Nails',
        'lashes': 'Lashes',
        'massage': 'Massage',
        'hair': 'Haircare',
        'facial': 'Facial',
        'nav_bookings': 'Bookings',
        'nav_favorites': 'Favorites',
        'nav_support': 'Support',
        'nav_search': 'Search',
        'nav_giftcards': 'Gift Cards',
        'nav_settings': 'Settings',
        'nav_guides': 'Guides',
        'nav_rewards': 'Rewards',
        'nav_inbox': 'Inbox',
        'action_register_business': 'Start as studio',
        'action_login': 'Login',
        'my_pages': 'My Pages',
        'location_title': 'Select Location',
        'location_search_placeholder': 'Search municipality...',
        'home_hero_title': 'Booking made easier',
        'home_hero_subtitle': 'A hassle-free experience for both clients and professionals.\nNo complicated administration, just pure focus on passion.',
        'home_hero_cta_book': 'Book Now',
        'home_hero_cta_register': 'Start as studio',
        'home_categories_title': 'Our Categories',
        'why_title': 'Why Glowbook',
        'why_card_1_title': 'Premium Clients',
        'why_card_1_desc': 'Reach the right audience and build a stronger client base',
        'why_card_2_title': 'Smart Visibility',
        'why_card_2_desc': 'Visible based on quality, not just price',
        'why_card_3_title': 'Easy Booking',
        'why_card_3_desc': 'Everything in one place without hassle',
        'why_card_4_title': 'Build your brand',
        'why_card_4_desc': 'Glowbook is not just booking, it is status',
        'home_view_all': 'View all',
        'cat_nails_name': 'Nails',
        'cat_nails_desc': 'Minimalist nail care & design',
        'cat_lashes_name': 'Lashes & Brows',
        'cat_lashes_desc': 'Lift your gaze with perfect shape',
        'cat_massage_name': 'Massage',
        'cat_massage_desc': 'Deep relaxation for the mind',
        'cat_skin_name': 'Skincare',
        'cat_skin_desc': 'Hydrating facial care & glow',
        'cat_hair_name': 'Haircare',
        'cat_hair_desc': 'Cut, color & styling',
        'cat_injection_name': 'Aesthetic Injection',
        'cat_injection_desc': 'Fillers, botox & skin rejuvenation',
        'cat_tattoo_name': 'Tattoo',
        'cat_tattoo_desc': 'Art on skin, from fine lines to realism',
        'cat_spa_name': 'Spa',
        'cat_spa_desc': 'Total relaxation & wellness',
        'cat_makeup_name': 'Makeup',
        'cat_makeup_desc': 'Professional styling for every occasion',
        'cat_footcare_name': 'Footcare',
        'cat_footcare_desc': 'Medical & cosmetic footcare',
        'cat_chiro_name': 'Chiropractic',
        'cat_chiro_desc': 'Joint & muscle treatment',
        'cat_naprapathy_name': 'Naprapathy',
        'cat_naprapathy_desc': 'Manual treatment of pain',
        'cat_teeth_name': 'Teeth Whitening',
        'cat_teeth_desc': 'Professional whiter smile',
        'cat_piercing_name': 'Piercing',
        'cat_piercing_desc': 'Safe & stylish piercing',
        'cat_barber_name': 'Barber',
        'cat_barber_desc': 'Classic mens cut & shave',
        'onboarding_title_1': 'Define your studio',
        'onboarding_title_2': 'Who is behind it?',
        'onboarding_title_3': 'Choose your growth plan',
        'onboarding_title_4': 'Secure Checkout',
        'onboarding_desc_1': 'Let premium clients find you in your city.',
        'onboarding_desc_2': 'Your data is safe and encrypted.',
        'onboarding_desc_3': 'Choose binding time to lower your monthly cost.',
        'onboarding_desc_4': 'Complete your order securely with Klarna.',
        'onboarding_step_1': 'Business',
        'onboarding_step_2': 'Personal',
        'onboarding_step_3': 'Subscription',
        'onboarding_step_4': 'Payment',
        'label_business_name': 'Business Name',
        'placeholder_business_name': 'E.g. Glow Nails & Spa',
        'label_category': 'Category',
        'label_country': 'Country',
        'label_municipality': 'Municipality',
        'label_address': 'Address',
        'label_optional': '(Optional)',
        'btn_next': 'Next',
        'btn_back': 'Back',
        'btn_complete_klarna': 'Complete purchase with Klarna.',
        'dash_welcome': 'Welcome',
        'dash_overview': 'Here is an overview of your business.',
        'dash_stat_bookings': 'Bookings today',
        'dash_stat_customers': 'New customers',
        'dash_stat_revenue': 'Revenue',
        'dash_stat_points': 'Glow Points',
        'dash_nav_customers': 'Customer Register',
        'dash_nav_customers_desc': 'See all existing customers, history and contact details.',
        'dash_nav_services': 'Services',
        'dash_nav_services_desc': 'Create new services, set prices and times, and customize your profile.',
        'dash_nav_finance': 'Finances',
        'dash_nav_finance_desc': 'See revenue from Klarna and approve payments made on site.',
        'dash_nav_settings': 'Settings',
        'dash_nav_settings_desc': 'Manage your salon details, personal info and membership.',
        'dash_bookings_title': 'Bookings',
        'dash_new_booking': 'New booking',
        'dash_no_bookings': 'No bookings yet',
        'dash_no_bookings_desc': 'There are no bookings registered for this week.',
        'settings_title': 'Settings',
        'settings_desc': 'Manage your profile, details and membership.',
        'tab_profile': 'Profile & Account',
        'tab_membership': 'Membership',
        'tab_notifications': 'Notifications',
        'tab_templates': 'Message Templates',
        'templates_title': 'Your Message Templates',
        'templates_desc': 'Create ready-made answers for common questions like directions and booking policy.',
        'templates_label_directions': 'Directions',
        'templates_label_policy': 'Booking Policy',
        'templates_label_preparation': 'Before the visit',
        'templates_save_btn': 'Save all templates',
        'tab_practitioners': 'Practitioners',
        'practitioners_title': 'Manage practitioners',
        'practitioners_desc': 'Add staff to your account so clients can choose who to book with.',
        'practitioners_add_btn': 'Add practitioner',
        'label_select_practitioner': 'Select practitioner',
        'label_preferred_practitioner': 'Preferred practitioner',
        'label_total_cost': 'Total cost',
        'label_per_month': 'per month',
        'share_link_title': 'Share available time',
        'share_link_desc': 'Generate a link to share on Instagram so clients can book directly.',
        'share_link_btn': 'Get link',
        'verification_modal_title': 'Verified account',
        'verification_modal_desc': 'Upload your certificate, diploma or other proof of competence. Our admins review your profile manually within a week.',
        'verification_upload_btn': 'Upload diploma/certificate',
        'verification_submit_btn': 'Submit for review',
        'verification_status_pending': 'Review in progress (est. 7 days)',
        'tab_marketing': 'Marketing',
        'tab_reviews': 'Reviews',
        'reviews_title': 'Manage reviews',
        'reviews_desc': 'See what your clients think and reply to their feedback.',
        'review_reply_label': 'Your reply',
        'review_reply_placeholder': 'Write a reply...',
        'review_reply_btn': 'Reply',
        'review_replied': 'Reply sent!',
        'marketing_title': 'Share your profile',
        'marketing_desc': 'Find tools to reach more clients and simplify booking.',
        'profile_link_label': 'Your profile link',
        'copy_link_btn': 'Copy link',
        'link_copied': 'Link copied!',
        'ig_link_label': 'Link for Instagram Bio',
        'ig_link_desc': 'Use this link to send clients directly to your bookable times.',
        'qr_title': 'Your QR code',
        'qr_desc': 'Download your unique QR code and use it on mirrors, business cards or social media.',
        'download_qr': 'Download QR (PNG)',
        'booking_card_title': 'Your Booking Cards',
        'booking_card_desc': 'Auto-generate beautiful images for your Instagram Story or posts.',
        'card_tpl_available': 'Available times',
        'card_tpl_new_service': 'New treatment',
        'card_tpl_last_slots': 'Last slots',
        'download_card': 'Save as image',
        'next_available_label': 'Next available time',
        'settings_salon_title': 'Salon Details',
        'settings_personal_title': 'Personal Details',
        'label_first_name': 'First Name',
        'label_last_name': 'Last Name',
        'label_email': 'Email',
        'btn_save_changes': 'Save all changes',
        'msg_changes_saved': 'Changes saved',
        'logout': 'Log out',
        'action_register': 'Create account',
        'role_customer': 'Customer',
        'role_provider': 'Practitioner',
        'role_admin': 'Admin',
        'label_password': 'Password',
        'action_login_prompt': 'Already have an account?',
        'msg_fill_all_fields': 'Please fill all required fields',
        'btn_change': 'Change',
        'cal_today': 'Today',
        'cal_week': 'Week',
        'cal_add_slot': 'Add slots',
        'cal_post_times': 'Post times in frame',
        'cal_go_to': 'Go to calendar',
        'btn_save_schedule': 'Save schedule',
        'explore_title': 'Discover beauty',
        'filter_placeholder': 'Filter results...',
        'found': 'Found',
        'free_today': 'Free today',
        'view_profile': 'View profile',
        'from': 'From',
        'in': 'in',
        'action_manage_customers': 'Manage customers',
        'action_edit_menu': 'Edit menu',
        'action_view_payouts': 'View payouts',
        'action_go_to_settings': 'Go to settings',
        'label_address_placeholder': 'Street address',
        'label_main_category': 'Main Category',
        'msg_contact_support_category': 'Contact support to change industry category.',
        'label_your_membership': 'Your membership',
        'label_status_active': 'Active',
        'label_months': 'months',
        'action_upgrade_plan': 'Upgrade plan',
        'action_downgrade_cancel': 'Downgrade / Cancel',
        'desc_notifications_settings': 'Manage your notification settings.',
        'notif_new_bookings': 'New bookings',
        'notif_new_bookings_desc': 'Get notified when a client books a time',
        'notif_cancellations': 'Cancellations',
        'notif_cancellations_desc': 'Get notified when a booking is cancelled',
        'notif_reminders': 'Reminders',
        'notif_reminders_desc': 'Daily summary of upcoming bookings',
        'notif_marketing': 'Marketing',
        'notif_marketing_desc': 'News and offers from Glowbook',
        'notif_klarna_connecting': 'Connecting to Klarna...',
        'notif_klarna_processing': 'Processing subscription...',
        'notif_klarna_success': 'Payment approved!',
        'notif_klarna_redirecting': 'Redirecting to your dashboard...',
        'notif_klarna_secure': 'Encrypted and secure connection',
        'action_cancel_purchase': 'Cancel purchase',
        'label_amount_to_pay': 'Amount to pay now',
        'msg_klarna_subscription': 'Handled as a subscription via Klarna Payments',
        'label_select_category': 'Select category',
        'msg_personal_data_warning': 'This data is only used for verification and billing. It will not be shown publicly on your profile.',
        'label_last_name_placeholder': 'Your last name',
        'label_first_name_placeholder': 'Your first name',
        'label_tier_start_desc': '20 bookings/month',
        'label_tier_pro_desc': 'Grow faster & more visibility',
        'label_tier_studio_desc': 'for larger salons',
        'label_most_popular': 'MOST POPULAR',
        'label_total': 'Total',
        'msg_one_month_free': '1 month free',
        'label_order_summary': 'Your Order',
        'label_subscription_length': 'Subscription length',
        'msg_terms_agreement': 'By proceeding you confirm that you accept Glowbook terms of use and privacy policy.',
        'label_renewal_automatic': 'Automatic renewal',
        'action_manage_subscription': 'Manage subscription',
        'label_active': 'Active',
        'action_select': 'Select',
        'notif_payment_notice': 'Payment info',
        'msg_payment_one_time': 'Your subscription will be charged as a one-time cost via Klarna on renewal.',
        'btn_save_subscription': 'Update subscription',
        'day_monday': 'Monday',
        'day_tuesday': 'Tuesday',
        'day_wednesday': 'Wednesday',
        'day_thursday': 'Thursday',
        'day_friday': 'Friday',
        'day_saturday': 'Saturday',
        'day_sunday': 'Sunday',
        'msg_invalid_time_range': 'End time must be after start time',
        'salon_appearance_title': 'Salon Appearance',
        'salon_appearance_desc': 'Upload images representing your business.',
        'label_background_image': 'Background image (1200x400)',
        'action_change_background': 'Change background',
        'action_update': 'Update',
        'action_create_service': 'Create new service',
        'label_niche_suggestions': 'Niche Picks',
        'label_suggestions_for': 'Suggestions for your category',
        'label_service_name': 'Service name',
        'label_price': 'Price',
        'label_time': 'Time',
        'label_description': 'Description',
        'placeholder_description': 'Briefly describe the service...',
        'btn_save_service': 'Save service',
        'nav_profile': 'Profile',
        'nav_dashboard': 'Dashboard',
        'nav_services': 'Services',
        'nav_staff': 'Staff',
        'nav_calendar': 'Calendar',
        'nav_clients': 'Clients',
        'nav_marketing': 'Marketing',
        'nav_finances': 'Finances',
        'nav_logout': 'Logout'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('Svenska');
    const [currency, setCurrency] = useState<string>('SEK');

    useEffect(() => {
        // 1. Try to load specifically saved language first
        const savedLang = localStorage.getItem('glowbook_language');
        if (savedLang) {
            setLanguage(savedLang as Language);
            return;
        }

        // 2. Fallback to salon data if available
        const savedSalon = localStorage.getItem('glowbook_salon');
        if (savedSalon) {
            const data = JSON.parse(savedSalon);
            if (data.country) {
                const countryData = NORDIC_COUNTRIES.find(c => c.name === data.country);
                if (countryData) {
                    setLanguage(countryData.language as Language);
                    setCurrency(countryData.currency);
                    return;
                }
            }
        }

        // 3. Fallback to browser language
        const browserLang = typeof navigator !== 'undefined' ? navigator.language.toLowerCase() : '';
        if (browserLang.includes('no')) setLanguage('Norska');
        else if (browserLang.includes('da')) setLanguage('Danska');
        else if (browserLang.includes('fi')) setLanguage('Finska');
        else if (browserLang.includes('is')) setLanguage('Isländska');
        else setLanguage('Svenska');
    }, []);

    // Persist language changes
    useEffect(() => {
        localStorage.setItem('glowbook_language', language);
    }, [language]);

    useEffect(() => {
        const matchingCountry = NORDIC_COUNTRIES.find(c => c.language === language);
        if (matchingCountry) {
            setCurrency(matchingCountry.currency);
        }
    }, [language]);

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, currency, setCurrency, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
